/**
 * KOL Education Service - Passive College Credit & Resume Building
 * Helps earn college credit and build resume using free resources
 * Low-pressure, automated tracking and suggestions
 */

import { db } from '../../services/db';

export interface CourseProgress {
  id: string;
  platform: string;
  courseName: string;
  provider: string;
  creditType: 'ACE' | 'CLEP' | 'DSST' | 'Coursera' | 'edX' | 'OpenStax' | 'Khan' | 'MIT' | 'Portfolio';
  creditHours: number;
  progress: number; // 0-100
  timeSpent: number; // minutes
  startDate: string;
  completionDate?: string;
  certificateUrl?: string;
  costSavings: number; // money saved vs traditional college
  status: 'not-started' | 'in-progress' | 'completed' | 'paused';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  tags: string[];
  notes: string;
  resumeReady: boolean;
}

export interface ResumeEntry {
  id: string;
  type: 'education' | 'certification' | 'project' | 'skill' | 'volunteer' | 'achievement';
  title: string;
  organization: string;
  description: string;
  startDate: string;
  endDate?: string;
  ongoing: boolean;
  skills: string[];
  url?: string;
  verified: boolean;
  autoGenerated: boolean;
  sourceId?: string; // links to course/project
}

export interface LearningGoal {
  id: string;
  category: 'career' | 'personal' | 'creative' | 'health' | 'advocacy';
  goal: string;
  targetCredits: number;
  currentCredits: number;
  deadline?: string;
  priority: 'low' | 'medium' | 'high';
  courses: string[]; // course IDs
}

// Free College Credit Resources
export const FREE_CREDIT_PLATFORMS = {
  // ACE Credit Recommendations (accepted by 2000+ colleges)
  ace: {
    sophia: {
      name: 'Sophia Learning',
      url: 'https://www.sophia.org',
      cost: 'Free trial, then $99/month (unlimited courses)',
      creditType: 'ACE',
      courses: [
        { name: 'English Composition I', credits: 3, time: '60 hours' },
        { name: 'English Composition II', credits: 3, time: '60 hours' },
        { name: 'College Algebra', credits: 3, time: '45 hours' },
        { name: 'Introduction to Psychology', credits: 3, time: '45 hours' },
        { name: 'Introduction to Sociology', credits: 3, time: '45 hours' },
        { name: 'Microeconomics', credits: 3, time: '60 hours' },
        { name: 'Macroeconomics', credits: 3, time: '60 hours' },
        { name: 'Environmental Science', credits: 3, time: '60 hours' },
        { name: 'Project Management', credits: 3, time: '60 hours' },
        { name: 'Web Development', credits: 3, time: '60 hours' }
      ]
    },
    study: {
      name: 'Study.com',
      url: 'https://study.com',
      cost: '$199.99/month (unlimited courses)',
      creditType: 'ACE',
      courses: [
        { name: 'US History I', credits: 3, time: '80 hours' },
        { name: 'US History II', credits: 3, time: '80 hours' },
        { name: 'Biology', credits: 3, time: '100 hours' },
        { name: 'Chemistry', credits: 3, time: '100 hours' },
        { name: 'Statistics', credits: 3, time: '80 hours' },
        { name: 'Business Law', credits: 3, time: '80 hours' }
      ]
    },
    straighterline: {
      name: 'StraighterLine',
      url: 'https://www.straighterline.com',
      cost: '$99/month + $59 per course',
      creditType: 'ACE',
      courses: [
        { name: 'Accounting I', credits: 3, time: '60 hours' },
        { name: 'Accounting II', credits: 3, time: '60 hours' },
        { name: 'Business Communications', credits: 3, time: '45 hours' },
        { name: 'Introduction to Business', credits: 3, time: '45 hours' }
      ]
    }
  },
  
  // CLEP Exams (completely free study resources)  clep: {
    modernstates: {
      name: 'Modern States (100% Free CLEP Prep)',
      url: 'https://modernstates.org',
      cost: 'FREE + covers exam fees',
      creditType: 'CLEP',
      exams: [
        { name: 'College Composition', credits: 6, prep: '40 hours', examCost: '$89 (covered)' },
        { name: 'Spanish Language', credits: 6, prep: '50 hours', examCost: '$89 (covered)' },
        { name: 'French Language', credits: 6, prep: '50 hours', examCost: '$89 (covered)' },
        { name: 'American Literature', credits: 3, prep: '30 hours', examCost: '$89 (covered)' },
        { name: 'Analyzing Literature', credits: 3, prep: '30 hours', examCost: '$89 (covered)' },
        { name: 'US History I', credits: 3, prep: '40 hours', examCost: '$89 (covered)' },
        { name: 'US History II', credits: 3, prep: '40 hours', examCost: '$89 (covered)' },
        { name: 'Western Civilization I', credits: 3, prep: '40 hours', examCost: '$89 (covered)' },
        { name: 'Biology', credits: 3, prep: '60 hours', examCost: '$89 (covered)' },
        { name: 'Chemistry', credits: 3, prep: '60 hours', examCost: '$89 (covered)' },
        { name: 'College Algebra', credits: 3, prep: '40 hours', examCost: '$89 (covered)' },
        { name: 'Precalculus', credits: 3, prep: '40 hours', examCost: '$89 (covered)' },
        { name: 'Calculus', credits: 3, prep: '50 hours', examCost: '$89 (covered)' },
        { name: 'Psychology', credits: 3, prep: '35 hours', examCost: '$89 (covered)' },
        { name: 'Sociology', credits: 3, prep: '35 hours', examCost: '$89 (covered)' }
      ]
    }
  },

  // Massive Open Online Courses (MOOCs) - Free Certificates
  moocs: {
    coursera: {
      name: 'Coursera',
      url: 'https://www.coursera.org',
      cost: 'Audit for FREE, $49 for certificate',
      financialAid: 'Available for most courses',
      programs: [
        { name: 'Google IT Support Professional Certificate', credits: 'Portfolio', time: '6 months' },
        { name: 'Google Data Analytics', credits: 'Portfolio', time: '6 months' },
        { name: 'IBM Data Science', credits: 'Portfolio', time: '8 months' },
        { name: 'Meta Social Media Marketing', credits: 'Portfolio', time: '5 months' },
        { name: 'Yale: Introduction to Psychology', credits: 'Portfolio', time: '16 hours' }
      ]
    },
    edx: {
      name: 'edX',
      url: 'https://www.edx.org',
      cost: 'Audit for FREE, $50-300 for certificate',
      programs: [
        { name: 'Harvard CS50', credits: 'Portfolio', time: '12 weeks' },
        { name: 'MIT Introduction to Computer Science', credits: 'Portfolio', time: '9 weeks' },
        { name: 'Berkeley Data Science', credits: 'Portfolio', time: '8 weeks' },
        { name: 'MicroMasters Programs', credits: 'Some ACE', time: 'Varies' }
      ]
    },
    khanacademy: {
      name: 'Khan Academy',
      url: 'https://www.khanacademy.org',
      cost: 'Completely FREE',
      subjects: [
        'Math (K-12 through Calculus)',
        'Science (Biology, Chemistry, Physics)',
        'Economics & Finance',
        'Computing (JavaScript, SQL, Web Dev)',
        'Arts & Humanities',
        'Test Prep (SAT, MCAT, etc.)'
      ]
    },
    mitocw: {
      name: 'MIT OpenCourseWare',
      url: 'https://ocw.mit.edu',
      cost: 'Completely FREE',
      note: 'Full MIT courses, no credit but portfolio-worthy',
      courses: [
        'Computer Science',
        'Mathematics',
        'Engineering',
        'Science',
        'Social Sciences'
      ]
    }
  },

  // Open Educational Resources
  oer: {
    openstax: {
      name: 'OpenStax',
      url: 'https://openstax.org',
      cost: 'FREE textbooks',
      subjects: [
        'Biology', 'Chemistry', 'Physics',
        'Math', 'Statistics',
        'Economics', 'Psychology', 'Sociology',
        'History', 'Business'
      ]
    },
    saylor: {
      name: 'Saylor Academy',
      url: 'https://www.saylor.org',
      cost: 'Completely FREE',
      creditType: 'ACE for some courses',
      courses: [
        'Business Administration',
        'Computer Science',
        'English',
        'History',
        'Mathematics',
        'Philosophy'
      ]
    }
  },

  // Portfolio Building Platforms
  portfolio: {
    github: {
      name: 'GitHub',
      url: 'https://github.com',
      cost: 'FREE',
      use: 'Code portfolio, contributions, projects'
    },
    behance: {
      name: 'Behance',
      url: 'https://www.behance.net',
      cost: 'FREE',
      use: 'Creative portfolio (art, design, photography)'
    },
    medium: {
      name: 'Medium',
      url: 'https://medium.com',
      cost: 'FREE to publish',
      use: 'Writing portfolio, thought leadership'
    },
    youtube: {
      name: 'YouTube',
      url: 'https://youtube.com',
      cost: 'FREE',
      use: 'Video portfolio, tutorials, content creation'
    }
  }
};

// Resume-Building Activities
export const RESUME_BUILDERS = {
  volunteer: [
    {
      platform: 'VolunteerMatch',
      url: 'https://www.volunteermatch.org',
      type: 'Virtual & Local opportunities',
      skills: ['Leadership', 'Communication', 'Project Management']
    },
    {
      platform: 'Catchafire',
      url: 'https://www.catchafire.org',
      type: 'Skills-based volunteering',
      skills: ['Marketing', 'Design', 'Tech', 'Writing']
    },
    {
      platform: 'UN Volunteers',
      url: 'https://www.unv.org',
      type: 'International development',
      skills: ['Research', 'Translation', 'Advocacy']
    }
  ],
  
  competitions: [
    {
      name: 'Kaggle Competitions',
      url: 'https://www.kaggle.com/competitions',
      type: 'Data Science',
      frequency: 'Ongoing'
    },
    {
      name: 'HackerRank',
      url: 'https://www.hackerrank.com',
      type: 'Coding Challenges',
      frequency: 'Ongoing'
    },
    {
      name: 'Creative Competitions',
      url: 'https://www.callforentry.org',
      type: 'Art, Photography, Writing',
      frequency: 'Monthly'
    }
  ],

  certifications: [
    {
      name: 'Google Analytics',
      url: 'https://skillshop.withgoogle.com',
      cost: 'FREE',
      time: '4-6 hours',
      value: 'High'
    },
    {
      name: 'HubSpot Content Marketing',
      url: 'https://academy.hubspot.com',
      cost: 'FREE',
      time: '5 hours',
      value: 'High'
    },
    {
      name: 'Facebook Blueprint',
      url: 'https://www.facebook.com/business/learn',
      cost: 'FREE',
      time: '3-4 hours',
      value: 'Medium'
    },
    {
      name: 'Microsoft Office Specialist',
      url: 'https://docs.microsoft.com/learn',
      cost: 'FREE training, $100 exam',
      time: '20 hours',
      value: 'High'
    }
  ]
};

export class EducationService {
  // Calculate potential savings
  static calculateSavings(credits: number): number {
    const avgCreditCost = 400; // Average cost per credit hour
    return credits * avgCreditCost;
  }

  // Get personalized course recommendations
  static getRecommendations(interests: string[], careerGoals: string[]): CourseProgress[] {
    // This would be enhanced with AI later
    const recommendations: Partial<CourseProgress>[] = [];
    
    if (interests.includes('writing') || interests.includes('poetry')) {
      recommendations.push({
        platform: 'Modern States',
        courseName: 'College Composition',
        provider: 'CLEP',
        creditType: 'CLEP',
        creditHours: 6,
        costSavings: 2400,
        difficulty: 'beginner',
        tags: ['writing', 'english', 'communication']
      });
    }

    if (interests.includes('psychology') || interests.includes('mental health')) {
      recommendations.push({
        platform: 'Sophia Learning',
        courseName: 'Introduction to Psychology',
        provider: 'Sophia',
        creditType: 'ACE',
        creditHours: 3,
        costSavings: 1200,
        difficulty: 'beginner',
        tags: ['psychology', 'mental health', 'behavior']
      });
    }

    if (interests.includes('photography') || interests.includes('art')) {
      recommendations.push({
        platform: 'Coursera',
        courseName: 'Photography Basics and Beyond Specialization',
        provider: 'Michigan State University',
        creditType: 'Portfolio',
        creditHours: 0,
        costSavings: 0,
        difficulty: 'beginner',
        tags: ['photography', 'art', 'creative']
      });
    }

    return recommendations as CourseProgress[];
  }

  // Track daily learning (passive tracking)
  static async logLearningTime(courseId: string, minutes: number): Promise<void> {
    const course = await db.education.get(courseId);
    if (course) {
      course.timeSpent += minutes;
      course.progress = Math.min(100, course.progress + (minutes / 10)); // rough calculation
      await db.education.put(course);
    }
  }

  // Auto-generate resume entries from completed courses
  static async generateResumeEntry(course: CourseProgress): Promise<ResumeEntry> {
    return {
      id: `resume-${Date.now()}`,
      type: course.creditType === 'Portfolio' ? 'certification' : 'education',
      title: course.courseName,
      organization: course.provider,
      description: `Completed ${course.creditHours} credit hour course through ${course.platform}. ${course.tags.join(', ')}`,
      startDate: course.startDate,
      endDate: course.completionDate,
      ongoing: !course.completionDate,
      skills: course.tags,
      url: course.certificateUrl,
      verified: !!course.certificateUrl,
      autoGenerated: true,
      sourceId: course.id
    };
  }

  // Get weekly low-pressure suggestions
  static getWeeklySuggestions(): string[] {
    const day = new Date().getDay();
    const suggestions = [
      'Spend 15 minutes on Khan Academy today - your future self will thank you 💜',
      'Consider watching one MIT OpenCourseWare lecture this week',
      'Maybe explore a free Coursera course that interests you?',
      'No pressure, but a CLEP exam could save you $2400+ in tuition',
      'Your GitHub profile could use a small project update',
      'Quick win: Get a Google Analytics certification (4 hours, FREE)',
      'Rest day! Learning happens during rest too 🌙'
    ];
    return [suggestions[day]];
  }

  // Calculate total progress toward degree
  static calculateDegreeProgress(courses: CourseProgress[]): {
    totalCredits: number;
    completedCredits: number;
    percentComplete: number;
    moneySaved: number;
    associateDegree: number; // 60 credits
    bachelorsDegree: number; // 120 credits
  } {
    const completed = courses.filter(c => c.status === 'completed');
    const totalCredits = completed.reduce((sum, c) => sum + c.creditHours, 0);
    const moneySaved = completed.reduce((sum, c) => sum + c.costSavings, 0);

    return {
      totalCredits,
      completedCredits: totalCredits,
      percentComplete: (totalCredits / 120) * 100,
      moneySaved,
      associateDegree: (totalCredits / 60) * 100,
      bachelorsDegree: (totalCredits / 120) * 100
    };
  }
}

export default EducationService;