/**
 * AI Adaptation Engine Service
 * Transforms user artwork into various product formats for passive income
 */

export interface ArtworkInput {
  id: string;
  imageUrl: string;
  title: string;
  tags: string[];
}

export interface ProductOutput {
  id: string;
  sourceArtId: string;
  type: 'pod_tshirt' | 'pod_mug' | 'pod_poster' | 'digital_print' | 'digital_planner' | 'social_post' | 'pinterest_pin' | 'ebook_cover';
  title: string;
  description: string;
  tags: string[];
  mockupUrl: string;
  platform: 'etsy' | 'gumroad' | 'printful' | 'instagram' | 'pinterest' | 'shopify';
  price: number;
  status: 'draft' | 'ready' | 'published' | 'sold';
  earnings: number;
  createdAt: string;
}

export interface AdaptationOptions {
  targetProducts: ProductOutput['type'][];
  targetPlatforms: ProductOutput['platform'][];
  autoGenerateDescriptions: boolean;
  autoGenerateTags: boolean;
  priceStrategy: 'competitive' | 'premium' | 'budget';
}

export interface ArtworkAnalysis {
  colors: {
    dominant: string[];
    palette: string[];
    mood: string;
  };
  style: string;
  mood: string;
  themes: string[];
  suggestedProducts: ProductOutput['type'][];
  suggestedPlatforms: ProductOutput['platform'][];
  marketPotential: 'high' | 'medium' | 'low';
}

const STORAGE_KEY = 'ai_adaptation_products';

export class AIAdaptationEngine {
  private products: Map<string, ProductOutput> = new Map();

  constructor() {
    this.loadFromStorage();
  }

  /**
   * Analyze artwork using AI to determine colors, mood, style, and suggested products
   */
  analyzeArtwork(imageUrl: string): ArtworkAnalysis {
    // Simulate AI analysis with realistic mock data
    const styles = ['abstract', 'minimalist', 'vintage', 'modern', 'watercolor', 'geometric', 'illustrative', 'photographic'];
    const moods = ['calm', 'energetic', 'mysterious', 'joyful', 'professional', 'playful', 'elegant', 'bold'];
    const themes = ['nature', 'urban', 'fantasy', 'motivation', 'wellness', 'technology', 'art', 'lifestyle'];

    const colorPalettes = [
      { dominant: ['#2C3E50', '#E74C3C'], palette: ['#2C3E50', '#E74C3C', '#ECF0F1', '#95A5A6'], mood: 'bold' },
      { dominant: ['#3498DB', '#2ECC71'], palette: ['#3498DB', '#2ECC71', '#F1C40F', '#E8F8F5'], mood: 'fresh' },
      { dominant: ['#9B59B6', '#E67E22'], palette: ['#9B59B6', '#E67E22', '#F39C12', '#D7BDE2'], mood: 'creative' },
      { dominant: ['#34495E', '#95A5A6'], palette: ['#34495E', '#95A5A6', '#ECF0F1', '#BDC3C7'], mood: 'professional' },
      { dominant: ['#E91E63', '#FFC107'], palette: ['#E91E63', '#FFC107', '#FF5722', '#FCE4EC'], mood: 'vibrant' }
    ];

    const randomPalette = colorPalettes[Math.floor(Math.random() * colorPalettes.length)];
    const randomStyle = styles[Math.floor(Math.random() * styles.length)];
    const randomMood = moods[Math.floor(Math.random() * moods.length)];
    const randomThemes = this.getRandomItems(themes, 2 + Math.floor(Math.random() * 3));

    // Suggest products based on style and mood
    const suggestedProducts: ProductOutput['type'][] = [];
    const suggestedPlatforms: ProductOutput['platform'][] = [];

    if (['abstract', 'geometric', 'modern'].includes(randomStyle)) {
      suggestedProducts.push('pod_tshirt', 'pod_poster', 'digital_print');
      suggestedPlatforms.push('printful', 'etsy', 'gumroad');
    }

    if (['minimalist', 'illustrative'].includes(randomStyle)) {
      suggestedProducts.push('digital_planner', 'social_post', 'pinterest_pin');
      suggestedPlatforms.push('gumroad', 'pinterest', 'instagram');
    }

    if (['vintage', 'watercolor'].includes(randomStyle)) {
      suggestedProducts.push('pod_mug', 'ebook_cover', 'pod_poster');
      suggestedPlatforms.push('etsy', 'shopify', 'printful');
    }

    // Ensure at least some products are suggested
    if (suggestedProducts.length === 0) {
      suggestedProducts.push('pod_poster', 'digital_print', 'social_post');
      suggestedPlatforms.push('etsy', 'gumroad', 'instagram');
    }

    const marketPotential: 'high' | 'medium' | 'low' =
      suggestedProducts.length >= 5 ? 'high' :
      suggestedProducts.length >= 3 ? 'medium' : 'low';

    return {
      colors: {
        dominant: randomPalette.dominant,
        palette: randomPalette.palette,
        mood: randomPalette.mood
      },
      style: randomStyle,
      mood: randomMood,
      themes: randomThemes,
      suggestedProducts: [...new Set(suggestedProducts)],
      suggestedPlatforms: [...new Set(suggestedPlatforms)],
      marketPotential
    };
  }

  /**
   * Generate product variations from artwork
   */
  generateProductVariations(
    art: ArtworkInput,
    options: AdaptationOptions
  ): ProductOutput[] {
    const products: ProductOutput[] = [];
    const analysis = this.analyzeArtwork(art.imageUrl);

    for (const productType of options.targetProducts) {
      for (const platform of options.targetPlatforms) {
        // Check if this product type is suitable for this platform
        if (!this.isProductSuitableForPlatform(productType, platform)) {
          continue;
        }

        const product: ProductOutput = {
          id: this.generateId(),
          sourceArtId: art.id,
          type: productType,
          title: this.generateProductTitle(art.title, productType),
          description: options.autoGenerateDescriptions
            ? this.generateDescription(art, productType, platform)
            : '',
          tags: options.autoGenerateTags
            ? this.generateTags(art, platform)
            : art.tags,
          mockupUrl: this.generateMockup(art, productType),
          platform,
          price: this.suggestPrice(productType, platform, options.priceStrategy),
          status: 'draft',
          earnings: 0,
          createdAt: new Date().toISOString()
        };

        products.push(product);
        this.products.set(product.id, product);
      }
    }

    this.saveToStorage();
    return products;
  }

  /**
   * Generate mockup image URL
   */
  generateMockup(art: ArtworkInput, productType: string): string {
    // Simulate mockup generation with placeholder service
    const mockupTemplates: Record<string, string> = {
      pod_tshirt: 'https://via.placeholder.com/800x800/2C3E50/FFFFFF?text=T-Shirt+Mockup',
      pod_mug: 'https://via.placeholder.com/800x800/E74C3C/FFFFFF?text=Mug+Mockup',
      pod_poster: 'https://via.placeholder.com/800x1000/3498DB/FFFFFF?text=Poster+Mockup',
      digital_print: 'https://via.placeholder.com/1200x1600/9B59B6/FFFFFF?text=Digital+Print',
      digital_planner: 'https://via.placeholder.com/800x1000/2ECC71/FFFFFF?text=Digital+Planner',
      social_post: 'https://via.placeholder.com/1080x1080/E67E22/FFFFFF?text=Social+Post',
      pinterest_pin: 'https://via.placeholder.com/1000x1500/E91E63/FFFFFF?text=Pinterest+Pin',
      ebook_cover: 'https://via.placeholder.com/800x1200/34495E/FFFFFF?text=Ebook+Cover'
    };

    return mockupTemplates[productType] || 'https://via.placeholder.com/800x800/95A5A6/FFFFFF?text=Mockup';
  }

  /**
   * Generate AI-powered SEO description
   */
  generateDescription(
    art: ArtworkInput,
    productType: string,
    platform: string
  ): string {
    const analysis = this.analyzeArtwork(art.imageUrl);
    const productName = this.getProductTypeName(productType);
    const styleDesc = analysis.style;
    const moodDesc = analysis.mood;
    const themes = analysis.themes.join(', ');

    const templates: Record<string, string[]> = {
      etsy: [
        `Unique ${styleDesc} ${productName} featuring "${art.title}". Perfect for ${themes} lovers. ${moodDesc.charAt(0).toUpperCase() + moodDesc.slice(1)} design that adds personality to any space. High-quality materials and vibrant colors guaranteed.`,
        `Handcrafted ${productName} with original ${styleDesc} artwork. This ${moodDesc} piece captures the essence of ${themes}. Makes a thoughtful gift or a special treat for yourself. Shop now!`
      ],
      gumroad: [
        `Download this stunning ${styleDesc} ${productName} instantly! Features "${art.title}" - a ${moodDesc} design perfect for ${themes} enthusiasts. High-resolution files included.`,
        `Get instant access to this ${moodDesc} ${productName}. ${styleDesc.charAt(0).toUpperCase() + styleDesc.slice(1)} artwork that works great for ${themes} projects. Digital download, unlimited personal use.`
      ],
      printful: [
        `Premium ${productName} with ${styleDesc} "${art.title}" design. This ${moodDesc} piece brings ${themes} vibes to your collection. Print-on-demand quality with fast shipping.`,
        `On-demand ${productName} featuring exclusive ${styleDesc} art. ${moodDesc.charAt(0).toUpperCase() + moodDesc.slice(1)} and versatile, perfect for ${themes} fans.`
      ],
      instagram: [
        `✨ New ${productName} alert! ${styleDesc.charAt(0).toUpperCase() + styleDesc.slice(1)} vibes with a ${moodDesc} twist. Perfect for ${themes} lovers! Link in bio 🔗`,
        `Obsessed with this ${moodDesc} ${productName}! ${styleDesc.charAt(0).toUpperCase() + styleDesc.slice(1)} design inspired by ${themes}. Who else needs this? 💫`
      ],
      pinterest: [
        `${styleDesc.charAt(0).toUpperCase() + styleDesc.slice(1)} ${productName} | ${art.title} | Perfect for ${themes} | ${moodDesc.charAt(0).toUpperCase() + moodDesc.slice(1)} Design | Click to shop now!`,
        `Stunning ${productName} with ${styleDesc} art! ${moodDesc.charAt(0).toUpperCase() + moodDesc.slice(1)} and unique. Great for ${themes} enthusiasts. Save for later!`
      ],
      shopify: [
        `Transform your space with this ${styleDesc} ${productName}. "${art.title}" brings ${moodDesc} energy and ${themes} inspiration. Premium quality, satisfaction guaranteed.`,
        `Elevate your style with our ${moodDesc} ${productName}. ${styleDesc.charAt(0).toUpperCase() + styleDesc.slice(1)} design perfect for ${themes} lovers. Limited availability - order now!`
      ]
    };

    const platformTemplates = templates[platform] || templates['etsy'];
    return platformTemplates[Math.floor(Math.random() * platformTemplates.length)];
  }

  /**
   * Generate platform-optimized tags
   */
  generateTags(art: ArtworkInput, platform: string): string[] {
    const analysis = this.analyzeArtwork(art.imageUrl);
    const baseTags = [...art.tags];

    // Platform-specific tag strategies
    const platformTags: Record<string, string[]> = {
      etsy: [
        analysis.style + ' art',
        analysis.mood + ' design',
        'handmade',
        'unique gift',
        'home decor',
        ...analysis.themes.map(t => t + ' art')
      ],
      gumroad: [
        'digital download',
        analysis.style,
        'instant access',
        'printable',
        'creative resource',
        ...analysis.themes
      ],
      printful: [
        'print on demand',
        'custom ' + analysis.style,
        'pod',
        'dropshipping',
        ...analysis.themes
      ],
      instagram: [
        analysis.style + 'art',
        analysis.mood + 'vibes',
        'artistsoninstagram',
        'artforsale',
        ...analysis.themes.map(t => t.replace(' ', ''))
      ],
      pinterest: [
        analysis.style + ' design ideas',
        analysis.mood + ' inspiration',
        ...analysis.themes.map(t => t + ' aesthetic'),
        'buy now',
        'shop'
      ],
      shopify: [
        analysis.style,
        analysis.mood,
        'online store',
        'shop now',
        ...analysis.themes
      ]
    };

    const selectedTags = platformTags[platform] || platformTags['etsy'];
    const combinedTags = [...new Set([...baseTags, ...selectedTags])];

    // Return 8-15 tags
    return combinedTags.slice(0, 12);
  }

  /**
   * Suggest price based on market analysis
   */
  suggestPrice(
    productType: string,
    platform: string,
    strategy: 'competitive' | 'premium' | 'budget'
  ): number {
    // Base prices for different product types
    const basePrices: Record<string, number> = {
      pod_tshirt: 25,
      pod_mug: 15,
      pod_poster: 20,
      digital_print: 10,
      digital_planner: 15,
      social_post: 5,
      pinterest_pin: 3,
      ebook_cover: 50
    };

    // Platform multipliers
    const platformMultipliers: Record<string, number> = {
      etsy: 1.1,
      gumroad: 0.95,
      printful: 1.0,
      instagram: 0.9,
      pinterest: 0.85,
      shopify: 1.05
    };

    // Strategy multipliers
    const strategyMultipliers = {
      budget: 0.75,
      competitive: 1.0,
      premium: 1.4
    };

    const basePrice = basePrices[productType] || 20;
    const platformMultiplier = platformMultipliers[platform] || 1.0;
    const strategyMultiplier = strategyMultipliers[strategy];

    const calculatedPrice = basePrice * platformMultiplier * strategyMultiplier;

    // Round to .99 or .00
    return Math.round(calculatedPrice) - 0.01;
  }

  /**
   * Batch process multiple artworks
   */
  async batchAdapt(
    arts: ArtworkInput[],
    options: AdaptationOptions
  ): Promise<ProductOutput[]> {
    const allProducts: ProductOutput[] = [];

    for (const art of arts) {
      const products = this.generateProductVariations(art, options);
      allProducts.push(...products);

      // Simulate processing delay
      await new Promise(resolve => setTimeout(resolve, 100));
    }

    return allProducts;
  }

  /**
   * Get all products
   */
  getAllProducts(): ProductOutput[] {
    return Array.from(this.products.values());
  }

  /**
   * Get products by artwork ID
   */
  getProductsByArtwork(artworkId: string): ProductOutput[] {
    return this.getAllProducts().filter(p => p.sourceArtId === artworkId);
  }

  /**
   * Get product by ID
   */
  getProduct(id: string): ProductOutput | undefined {
    return this.products.get(id);
  }

  /**
   * Update product
   */
  updateProduct(id: string, updates: Partial<ProductOutput>): ProductOutput | null {
    const product = this.products.get(id);
    if (!product) return null;

    const updated = { ...product, ...updates };
    this.products.set(id, updated);
    this.saveToStorage();
    return updated;
  }

  /**
   * Delete product
   */
  deleteProduct(id: string): boolean {
    const deleted = this.products.delete(id);
    if (deleted) {
      this.saveToStorage();
    }
    return deleted;
  }

  /**
   * Get total earnings
   */
  getTotalEarnings(): number {
    return this.getAllProducts().reduce((sum, p) => sum + p.earnings, 0);
  }

  /**
   * Get earnings by platform
   */
  getEarningsByPlatform(): Record<string, number> {
    const earnings: Record<string, number> = {};

    for (const product of this.getAllProducts()) {
      if (!earnings[product.platform]) {
        earnings[product.platform] = 0;
      }
      earnings[product.platform] += product.earnings;
    }

    return earnings;
  }

  /**
   * Get product statistics
   */
  getStatistics() {
    const products = this.getAllProducts();
    const byStatus = products.reduce((acc, p) => {
      acc[p.status] = (acc[p.status] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const byType = products.reduce((acc, p) => {
      acc[p.type] = (acc[p.type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const byPlatform = products.reduce((acc, p) => {
      acc[p.platform] = (acc[p.platform] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return {
      total: products.length,
      byStatus,
      byType,
      byPlatform,
      totalEarnings: this.getTotalEarnings(),
      earningsByPlatform: this.getEarningsByPlatform()
    };
  }

  /**
   * Clear all products
   */
  clearAll(): void {
    this.products.clear();
    this.saveToStorage();
  }

  // Private helper methods

  private generateId(): string {
    return `prod_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  private generateProductTitle(artTitle: string, productType: string): string {
    const productNames: Record<string, string> = {
      pod_tshirt: 'T-Shirt',
      pod_mug: 'Mug',
      pod_poster: 'Poster',
      digital_print: 'Digital Print',
      digital_planner: 'Digital Planner',
      social_post: 'Social Media Post',
      pinterest_pin: 'Pinterest Pin',
      ebook_cover: 'Ebook Cover'
    };

    return `${artTitle} - ${productNames[productType] || 'Product'}`;
  }

  private getProductTypeName(productType: string): string {
    const names: Record<string, string> = {
      pod_tshirt: 't-shirt',
      pod_mug: 'mug',
      pod_poster: 'poster',
      digital_print: 'digital print',
      digital_planner: 'planner',
      social_post: 'social media graphic',
      pinterest_pin: 'Pinterest pin',
      ebook_cover: 'ebook cover'
    };

    return names[productType] || 'product';
  }

  private isProductSuitableForPlatform(
    productType: ProductOutput['type'],
    platform: ProductOutput['platform']
  ): boolean {
    const suitability: Record<string, string[]> = {
      pod_tshirt: ['etsy', 'printful', 'shopify'],
      pod_mug: ['etsy', 'printful', 'shopify'],
      pod_poster: ['etsy', 'printful', 'shopify'],
      digital_print: ['etsy', 'gumroad', 'shopify'],
      digital_planner: ['etsy', 'gumroad', 'shopify'],
      social_post: ['instagram', 'gumroad'],
      pinterest_pin: ['pinterest', 'gumroad'],
      ebook_cover: ['etsy', 'gumroad', 'shopify']
    };

    return suitability[productType]?.includes(platform) || false;
  }

  private getRandomItems<T>(array: T[], count: number): T[] {
    const shuffled = [...array].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  }

  private saveToStorage(): void {
    try {
      const data = Array.from(this.products.values());
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    } catch (error) {
      console.error('Failed to save products to storage:', error);
    }
  }

  private loadFromStorage(): void {
    try {
      const data = localStorage.getItem(STORAGE_KEY);
      if (data) {
        const products: ProductOutput[] = JSON.parse(data);
        this.products = new Map(products.map(p => [p.id, p]));
      }
    } catch (error) {
      console.error('Failed to load products from storage:', error);
    }
  }
}

// Export singleton instance
export const aiAdaptationEngine = new AIAdaptationEngine();

// Export class for testing
export default AIAdaptationEngine;
