openapi: 3.0.1
info:
  title: Coursera OAuth2 API
  version: 1.0.0
servers:
  - url: 'https://api.coursera.com'
paths:
  /oauth2/client_credentials/token:
    post:
      summary: Get client credentials token
      operationId: getClientCredentialsToken
      requestBody:
        description: |
          Send a request with grant_type URL-encoded, and an Authorization header containing a Base64 encoded value of your app key and secret separated by a semicolon (e.g., key:secret)
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - grant_type
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                  default: client_credentials
                  readOnly: true
      responses:
        '200':
          description: Client credentials token is successfully generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientCredentialsTokenResponse'
      security:
        - BasicAuth: []
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    ClientCredentialsTokenResponse:
      type: object
      properties:
        token_type:
          type: string
          example: Bearer
        access_token:
          type: string
          example: QBcxspDKGbbtJO4oIfzgXpO6WA7d
        grant_type:
          type: string
          example: client_credentials
        issued_at:
          type: integer
          format: int64
          example: 1686856416
        expires_in:
          type: integer
          format: int32
          example: 1799