import axios from 'axios';

export interface SpotifyTrack {
  id: string;
  name: string;
  artists: string[];
  album: string;
  duration_ms: number;
  uri: string;
  preview_url?: string;
}

export interface SpotifyPlaylist {
  id: string;
  name: string;
  description?: string;
  tracks: number;
  uri: string;
  images: { url: string }[];
}

export class SpotifyIntegration {
  private accessToken: string | null = null;
  private refreshToken: string | null = null;
  private clientId: string;
  private clientSecret: string;

  constructor() {
    this.clientId = process.env.SPOTIFY_CLIENT_ID || '';
    this.clientSecret = process.env.SPOTIFY_CLIENT_SECRET || '';
  }

  async authorize(code: string, redirectUri: string): Promise<void> {
    try {
      const response = await axios.post(
        'https://accounts.spotify.com/api/token',
        new URLSearchParams({
          grant_type: 'authorization_code',
          code,
          redirect_uri: redirectUri,
          client_id: this.clientId,
          client_secret: this.clientSecret,
        }),
        {
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        }
      );

      this.accessToken = response.data.access_token;
      this.refreshToken = response.data.refresh_token;
    } catch (error) {
      console.error('Spotify authorization failed:', error);
      throw new Error('Failed to authorize with Spotify');
    }
  }

  async getCurrentlyPlaying(): Promise<SpotifyTrack | null> {
    if (!this.accessToken) {
      throw new Error('Not authorized');
    }

    try {
      const response = await axios.get(
        'https://api.spotify.com/v1/me/player/currently-playing',
        {
          headers: { Authorization: `Bearer ${this.accessToken}` },
        }
      );

      if (!response.data.item) {
        return null;
      }

      return {
        id: response.data.item.id,
        name: response.data.item.name,
        artists: response.data.item.artists.map((a: any) => a.name),
        album: response.data.item.album.name,
        duration_ms: response.data.item.duration_ms,
        uri: response.data.item.uri,
        preview_url: response.data.item.preview_url,
      };
    } catch (error) {
      console.error('Error getting currently playing:', error);
      return null;
    }
  }

  async createPlaylistForMood(userId: string, mood: string): Promise<SpotifyPlaylist> {
    if (!this.accessToken) {
      throw new Error('Not authorized');
    }

    const moodSeeds: Record<string, string[]> = {
      energized: ['happy', 'energetic', 'party'],
      calm: ['chill', 'acoustic', 'ambient'],
      focused: ['concentration', 'study', 'instrumental'],
      sleepy: ['sleep', 'lullaby', 'meditation'],
      sad: ['sad', 'melancholy', 'rainy-day'],
      anxious: ['calming', 'peaceful', 'nature'],
    };

    const seeds = moodSeeds[mood.toLowerCase()] || ['chill'];

    try {
      // Get recommendations
      const recommendations = await axios.get(
        'https://api.spotify.com/v1/recommendations',
        {
          headers: { Authorization: `Bearer ${this.accessToken}` },
          params: {
            seed_genres: seeds.join(','),
            limit: 30,
            target_energy: mood === 'energized' ? 0.8 : mood === 'calm' ? 0.3 : 0.5,
            target_valence: mood === 'sad' ? 0.2 : mood === 'energized' ? 0.9 : 0.5,
          },
        }
      );

      // Create playlist
      const playlistResponse = await axios.post(
        `https://api.spotify.com/v1/users/${userId}/playlists`,
        {
          name: `Kol's Hub: ${mood.charAt(0).toUpperCase() + mood.slice(1)} Mood`,
          description: `Generated by Kol's Hub based on your ${mood} mood`,
          public: false,
        },
        {
          headers: { Authorization: `Bearer ${this.accessToken}` },
        }
      );

      const playlistId = playlistResponse.data.id;

      // Add tracks to playlist
      const trackUris = recommendations.data.tracks.map((t: any) => t.uri);
      await axios.post(
        `https://api.spotify.com/v1/playlists/${playlistId}/tracks`,
        { uris: trackUris },
        {
          headers: { Authorization: `Bearer ${this.accessToken}` },
        }
      );

      return {
        id: playlistId,
        name: playlistResponse.data.name,
        description: playlistResponse.data.description,
        tracks: trackUris.length,
        uri: playlistResponse.data.uri,
        images: playlistResponse.data.images || [],
      };
    } catch (error) {
      console.error('Error creating playlist:', error);
      throw new Error('Failed to create Spotify playlist');
    }
  }

  async playTrack(uri: string, deviceId?: string): Promise<void> {
    if (!this.accessToken) {
      throw new Error('Not authorized');
    }

    try {
      await axios.put(
        'https://api.spotify.com/v1/me/player/play',
        {
          uris: [uri],
          ...(deviceId && { device_id: deviceId }),
        },
        {
          headers: { Authorization: `Bearer ${this.accessToken}` },
        }
      );
    } catch (error) {
      console.error('Error playing track:', error);
      throw new Error('Failed to play track');
    }
  }

  async pausePlayback(): Promise<void> {
    if (!this.accessToken) {
      throw new Error('Not authorized');
    }

    try {
      await axios.put(
        'https://api.spotify.com/v1/me/player/pause',
        {},
        {
          headers: { Authorization: `Bearer ${this.accessToken}` },
        }
      );
    } catch (error) {
      console.error('Error pausing playback:', error);
    }
  }

  async getUserPlaylists(): Promise<SpotifyPlaylist[]> {
    if (!this.accessToken) {
      throw new Error('Not authorized');
    }

    try {
      const response = await axios.get('https://api.spotify.com/v1/me/playlists', {
        headers: { Authorization: `Bearer ${this.accessToken}` },
      });

      return response.data.items.map((item: any) => ({
        id: item.id,
        name: item.name,
        description: item.description,
        tracks: item.tracks.total,
        uri: item.uri,
        images: item.images,
      }));
    } catch (error) {
      console.error('Error getting playlists:', error);
      return [];
    }
  }
}
