import React, { useState } from 'react';
import { FileText, Download, Eye, Edit, Sparkles, Briefcase } from 'lucide-react';
import { useEducationStore } from '../store/educationStore';

const ResumeBuilder: React.FC = () => {
  const { resumeData, updateResume } = useEducationStore();
  const [activeSection, setActiveSection] = useState<'view' | 'edit'>('view');

  const autoGeneratedSkills = [
    'Health Data Management', 'Medication Tracking', 'Creative Writing',
    'Photography', 'Modeling', 'Performance Art', 'React Development',
    'TypeScript', 'Accessibility Design', 'UI/UX', 'Data Visualization'
  ];

  const experienceFromApp = [
    {
      title: 'Personal OS Developer',
      organization: 'Self-Directed Project',
      period: '2024 - Present',
      points: [
        'Developed comprehensive health tracking application using React and TypeScript',
        'Implemented accessibility-first design principles (WCAG AA compliant)',
        'Created 3D avatar integration system using Ready Player Me API',
        'Built offline-first data management system with IndexedDB'
      ]
    },
    {
      title: 'Creative Professional',
      organization: 'Freelance',
      period: '2020 - Present',
      points: [
        'Poetry, modeling, photography, and performance work',
        'Community organizing and activist work',
        'Digital content creation and social media management',
        'Cultural research and documentation'
      ]
    }
  ];

  return (
    <div className="space-y-6">
      {/* Auto-Update Notice */}
      <div className="bg-gradient-to-r from-purple-500/20 to-pink-500/20 backdrop-blur-xl rounded-2xl p-6 border border-purple-500/30">
        <div className="flex items-start gap-4">
          <Sparkles className="w-6 h-6 text-purple-400 flex-shrink-0 mt-1" />
          <div>
            <h3 className="font-semibold text-lg mb-2">Auto-Updating Resume</h3>
            <p className="text-gray-300 text-sm mb-3">
              Your resume automatically updates as you use the app! Every skill you log, 
              course you complete, and project you create gets added to your professional profile.
            </p>
            <div className="flex gap-3">
              <button className="px-4 py-2 bg-purple-500 hover:bg-purple-600 rounded-lg text-sm flex items-center gap-2 transition-all">
                <Download className="w-4 h-4" />
                Download PDF
              </button>
              <button className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-sm flex items-center gap-2 transition-all">
                <Edit className="w-4 h-4" />
                Customize
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Resume Preview */}
      <div className="bg-white text-black rounded-2xl p-8 shadow-2xl max-w-4xl">
        {/* Header */}
        <div className="border-b-4 border-purple-600 pb-6 mb-6">
          <h1 className="text-4xl font-bold text-purple-900">KOL</h1>
          <div className="text-lg text-gray-700 mt-1">Creative Professional • Scholar • Activist</div>
          <div className="flex gap-4 mt-3 text-sm text-gray-600">
            <span>Kansas City, MO</span>
            <span>•</span>
            <span>they/them</span>
            <span>•</span>
            <span>Available for projects</span>
          </div>
        </div>

        {/* Summary */}
        <section className="mb-6">
          <h2 className="text-2xl font-bold text-purple-900 mb-3">Professional Summary</h2>
          <p className="text-gray-700 leading-relaxed">
            Multidisciplinary creative and scholar with expertise in poetry, photography, modeling, 
            and performance. Strong background in health advocacy, accessibility design, and community 
            organizing. Proven ability to build innovative technological solutions while maintaining 
            trauma-informed and inclusive approaches.
          </p>
        </section>

        {/* Skills */}
        <section className="mb-6">
          <h2 className="text-2xl font-bold text-purple-900 mb-3">Skills & Expertise</h2>
          <div className="flex flex-wrap gap-2">
            {autoGeneratedSkills.map((skill, idx) => (
              <span
                key={idx}
                className="px-3 py-1 bg-purple-100 text-purple-800 rounded-full text-sm font-medium"
              >
                {skill}
              </span>
            ))}
          </div>
        </section>

        {/* Experience */}
        <section className="mb-6">
          <h2 className="text-2xl font-bold text-purple-900 mb-4">Experience</h2>
          <div className="space-y-5">
            {experienceFromApp.map((exp, idx) => (
              <div key={idx}>
                <div className="flex justify-between items-start mb-2">
                  <div>
                    <h3 className="text-lg font-bold text-gray-900">{exp.title}</h3>
                    <div className="text-gray-700">{exp.organization}</div>
                  </div>
                  <div className="text-sm text-gray-600">{exp.period}</div>
                </div>
                <ul className="list-disc list-inside space-y-1 text-gray-700">
                  {exp.points.map((point, pidx) => (
                    <li key={pidx} className="text-sm">{point}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>

        {/* Education */}
        <section>
          <h2 className="text-2xl font-bold text-purple-900 mb-3">Education & Certifications</h2>
          <div className="space-y-3">
            <div>
              <h3 className="font-bold text-gray-900">In Progress: Associate's Degree</h3>
              <div className="text-gray-700 text-sm">
                Alternative Credit Pathway • {resumeData?.totalCredits || 0} credits earned
              </div>
              <div className="text-gray-600 text-sm mt-1">
                CLEP, Sophia Learning, Study.com • Expected completion 2025
              </div>
            </div>
            
            <div className="text-sm text-gray-700">
              <div className="font-semibold">Completed Coursework:</div>
              <div className="text-gray-600">
                College Algebra, English Composition, US History, Introduction to Psychology, 
                Business Communication, Web Development Fundamentals
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* Resume Tips */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-blue-500/10 backdrop-blur-xl rounded-xl p-5 border border-blue-500/20">
          <div className="flex items-start gap-3">
            <Briefcase className="w-5 h-5 text-blue-400 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold mb-2">LinkedIn Optimization</h4>
              <p className="text-sm text-gray-300">
                Sync your resume with LinkedIn automatically. We'll suggest headline 
                improvements and skill endorsements based on your app activity.
              </p>
            </div>
          </div>
        </div>

        <div className="bg-green-500/10 backdrop-blur-xl rounded-xl p-5 border border-green-500/20">
          <div className="flex items-start gap-3">
            <FileText className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold mb-2">ATS-Friendly Format</h4>
              <p className="text-sm text-gray-300">
                Your resume is optimized for Applicant Tracking Systems (ATS). 
                It includes the right keywords and formatting to pass automated screenings.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResumeBuilder;
