import { WearableData, HealthPortalData } from '../types';

export class ReportGenerationService {
  async generateDoctorReport(
    userId: string,
    data: {
      vitals: any[];
      medications: any[];
      symptoms: any[];
      wearableData: WearableData[];
      healthPortalData?: HealthPortalData;
    },
    dateRange: { start: Date; end: Date }
  ): Promise<string> {
    const report = `
MEDICAL REPORT
Patient ID: ${userId}
Report Period: ${dateRange.start.toLocaleDateString()} - ${dateRange.end.toLocaleDateString()}
Generated: ${new Date().toLocaleString()}

===============================================

VITAL SIGNS SUMMARY
${this.formatVitals(data.vitals)}

CURRENT MEDICATIONS
${this.formatMedications(data.medications)}

SYMPTOMS TRACKED
${this.formatSymptoms(data.symptoms)}

WEARABLE DEVICE DATA
${this.formatWearableData(data.wearableData)}

${data.healthPortalData ? `PORTAL DATA\n${this.formatPortalData(data.healthPortalData)}` : ''}

===============================================

This report was generated by the Adaptive Support Hub system.
Please review with healthcare provider.
    `;

    return report.trim();
  }

  private formatVitals(vitals: any[]): string {
    if (vitals.length === 0) return 'No vitals recorded';

    return vitals
      .map(
        (v) =>
          `  ${new Date(v.timestamp).toLocaleDateString()}: ${v.type} = ${v.value} ${v.unit}`
      )
      .join('\n');
  }

  private formatMedications(medications: any[]): string {
    if (medications.length === 0) return 'No medications recorded';

    return medications
      .map(
        (m) =>
          `  - ${m.name} (${m.dosage})\n    Frequency: ${m.frequency}\n    Instructions: ${m.instructions}`
      )
      .join('\n\n');
  }

  private formatSymptoms(symptoms: any[]): string {
    if (symptoms.length === 0) return 'No symptoms recorded';

    return symptoms
      .map(
        (s) =>
          `  ${new Date(s.timestamp).toLocaleDateString()}: ${s.symptom} (Severity: ${s.severity}/10)`
      )
      .join('\n');
  }

  private formatWearableData(wearableData: WearableData[]): string {
    if (wearableData.length === 0) return 'No wearable data available';

    // Group by type
    const grouped = wearableData.reduce((acc, data) => {
      if (!acc[data.type]) {
        acc[data.type] = [];
      }
      acc[data.type].push(data);
      return acc;
    }, {} as Record<string, WearableData[]>);

    let output = '';
    for (const [type, dataPoints] of Object.entries(grouped)) {
      const avg = dataPoints.reduce((sum, d) => sum + d.value, 0) / dataPoints.length;
      output += `  ${type}: Average ${avg.toFixed(2)} ${dataPoints[0].unit}\n`;
    }

    return output;
  }

  private formatPortalData(portalData: HealthPortalData): string {
    let output = '';

    if (portalData.appointments && portalData.appointments.length > 0) {
      output += '  Upcoming Appointments:\n';
      output += portalData.appointments
        .map((a) => `    - ${a.description} (${new Date(a.start).toLocaleDateString()})`)
        .join('\n');
      output += '\n\n';
    }

    if (portalData.labResults && portalData.labResults.length > 0) {
      output += '  Recent Lab Results:\n';
      output += portalData.labResults
        .map((l) => `    - ${l.code}: ${JSON.stringify(l.value)}`)
        .join('\n');
    }

    return output;
  }

  async generatePrintableReport(
    userId: string,
    reportType: 'weekly' | 'monthly' | 'custom',
    data: any
  ): Promise<Buffer> {
    // In production, this would use a PDF library like pdfkit
    // For now, generate HTML that can be printed

    const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #2c3e50; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #4CAF50; color: white; }
    .header { text-align: center; margin-bottom: 40px; }
    @media print { .no-print { display: none; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>Health Report - ${reportType.toUpperCase()}</h1>
    <p>User ID: ${userId}</p>
    <p>Generated: ${new Date().toLocaleString()}</p>
  </div>

  <h2>Summary</h2>
  <p>Report contains health data, vitals, and wearable device metrics.</p>

  <button class="no-print" onclick="window.print()">Print Report</button>
</body>
</html>
    `;

    return Buffer.from(html);
  }

  async exportToCSV(userId: string, data: any[]): Promise<string> {
    if (data.length === 0) return '';

    // Get headers from first object
    const headers = Object.keys(data[0]);
    const csvRows = [headers.join(',')];

    // Add data rows
    for (const row of data) {
      const values = headers.map((header) => {
        const value = row[header];
        return typeof value === 'string' && value.includes(',')
          ? `"${value}"`
          : value;
      });
      csvRows.push(values.join(','));
    }

    return csvRows.join('\n');
  }
}
